from app.api.routes.auth import router as auth_router
from app.api.routes.notes import router as notes_router
from app.api.routes.folders import router as folders_router
from app.api.routes.tags import router as tags_router
from app.api.routes.search import router as search_router
from app.api.routes.graph import router as graph_router
from app.api.routes.categories import router as categories_router
from app.api.routes.contents import router as contents_router
from app.api.routes.skills import router as skills_router
from app.api.routes.prompts import router as prompts_router
from app.api.routes.smart_import import router as import_router
